COTIZACION_RUMBO = "RUMBO"
COTIZACION_ENDOSOS = "ENDOSOS"

EDAD_MINIMA_PARTICIPACION = 18
EDAD_MAXIMA_PERMANENCIA = 70

MINIMO_PERIODO_VIGENCIA = 1
MINIMO_PERIODO_PAGO_PRIMAS = 1

MINIMO_SUMAS_ASEGURADAS = 0

MINIMO_PRIMA = 0
MINIMO_PORCENTAJE_DEVOLUCION = 0

TASA_MENSUALIZACION = 0.0933333333333333
FACTOR_AJUSTE = 4.19
FACTOR_RESERVA = 0.5

ANUAL = 12
SEMESTRAL = 6
TRIMESTRAL = 3
MENSUAL = 1

PROBABILIDAD_VIVOS = 1

PERIODO_VIGENCIA_MAXIMO = 52
PERIODO_PAGO_PRIMAS_MAXIMO = 25

PERIODO_VIGENCIA_MINIMO = 1
PERIODO_PAGO_PRIMAS_MINIMO = 1

AJUSTE_MORTALIDAD_POR_DEFECTO = 150

"""
Constantes de configuración para el sistema de cotizaciones
"""

# Configuración de optimización - valores del algoritmo de bisección
PORCENTAJE_INICIAL = 100.0
PORCENTAJE_MAXIMO_INICIAL = 130.0
PORCENTAJE_LIMITE = 200.0
PASO_INCREMENTO = 10.0
TOLERANCIA = 1e-6
MAX_ITERACIONES = 50

# Configuración de cálculos actuariales
PROBABILIDAD_VIVOS_INICIAL = 1.0
MESES_POR_AÑO = 12
CONVERSION_PORMILL = 1000.0


# Clase para compatibilidad con el código existente
class ConfiguracionOptimizacion:
    PORCENTAJE_INICIAL = PORCENTAJE_INICIAL
    PORCENTAJE_MAXIMO = PORCENTAJE_MAXIMO_INICIAL
    PORCENTAJE_LIMITE = PORCENTAJE_LIMITE
    PASO = PASO_INCREMENTO
    TOLERANCIA = TOLERANCIA
    MAX_ITERACIONES = MAX_ITERACIONES
