COTIZACION_RUMBO = "RUMBO"
COTIZACION_ENDOSOS = "ENDOSOS"

EDAD_MINIMA_PARTICIPACION = 18
EDAD_MAXIMA_PERMANENCIA = 70

MINIMO_PERIODO_VIGENCIA = 1
MINIMO_PERIODO_PAGO_PRIMAS = 1

MINIMO_SUMAS_ASEGURADAS = 0

MINIMO_PRIMA = 0
MINIMO_PORCENTAJE_DEVOLUCION = 0

TASA_MENSUALIZACION = 0.0933333333333333
FACTOR_AJUSTE = 4.19
FACTOR_RESERVA = 0.5
